# Real code generation example supervised by PROMETHEUS
def generate_code(request: str):
    if "todo" in request.lower():
        code = '''# Todo App Example
from fastapi import FastAPI
app = FastAPI()

@app.get("/todos")
def get_todos():
    return {"todos": ["Buy milk", "Walk dog"]}'''
    else:
        code = "# Simple code generated by Forge under PROMETHEUS supervision"
    return code
